conn:
  server: '192.168.0.81:57314'
  cert: ''
  timeout:
    dial: 5s
    file: 1m
throughput:
  concurrency: 8
  chunk: 32768
  delay: 0s
files:
  patterns:
    - '/nsm/extracted/*'
  processed: '/nsm/strelkd/'
  delete: false
  gatekeeper: true
response:
  report: 5s
delta: 5s
staging: '/nsm/staging/'
